/**
 * API types — mirrors the Worker's serializers (backend/src/services/*).
 * Kept hand-written for now; a shared package is a later refactor.
 */

export type CaptionStatus =
  | 'PENDING'
  | 'QUEUED'
  | 'PROCESSING'
  | 'COMPLETED'
  | 'FAILED'
  | 'SKIPPED';

export type CaptionJobStatus = 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';

export type Platform =
  | 'YOUTUBE'
  | 'SOUNDCLOUD'
  | 'TWITTER'
  | 'TIKTOK'
  | 'INSTAGRAM'
  | 'TWITCH'
  | 'REDDIT'
  | 'DIRECT';

export interface MediaFile {
  id: string;
  mediaItemId: string;
  /** R2 object key — not a URL. Playback URLs are issued separately. */
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  isOriginal: boolean;
  format: string | null;
  createdAt: string;
}

export interface MediaItem {
  id: string;
  userId: string;
  originalUrl: string;
  platform: Platform;
  title: string;
  description: string | null;
  tags: string[];
  createdAt: string;
  updatedAt: string;

  captionStatus: CaptionStatus;
  captionErrorMessage: string | null;
  captionGeneratedAt: string | null;

  duration: number | null;
  size: number;
  format: string;
  resolution: string | null;
  thumbnailUrl: string | null;

  originalAuthor: string | null;
  originalTitle: string | null;
  originalDescription: string | null;
  publishedAt: string | null;
  hashtags: string[];

  files: MediaFile[];
}

export interface CaptionSegment {
  id: string;
  captionId: string;
  startTime: number;
  endTime: number;
  text: string;
  confidence: number | null;
}

export interface Caption {
  id: string;
  mediaItemId: string;
  language: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  segments: CaptionSegment[];
}

export interface CaptionJobInfo {
  id: string;
  status: CaptionJobStatus;
  attempts: number;
  maxAttempts: number;
}

export interface CaptionStatusResponse {
  captionStatus: CaptionStatus;
  errorMessage: string | null;
  generatedAt: string | null;
  job: CaptionJobInfo | null;
}

export interface StorageQuota {
  used: number;
  limit: number;
  hasSpace: boolean;
}

export interface AdminUser {
  id: string;
  uid: string;
  email: string | null;
  displayName: string | null;
}

export interface LoginResult {
  token: string;
  expiresAt: string;
  user: AdminUser;
}

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface UploadStartResult {
  mediaItemId: string;
  key: string;
  uploadUrl: string;
}

// ---------------------------------------------------------------------------
// Search (mirrors backend/src/services/search.ts)
// ---------------------------------------------------------------------------

/** Which field a result matched on. `lyrics` means the transcript. */
export type SearchMatchField = 'title' | 'tags' | 'description' | 'lyrics';

export interface SearchMatch {
  fields: SearchMatchField[];
  /** The best-matching transcript line, with the timestamp to seek to. */
  lyric: { text: string; startTime: number } | null;
}

/** A search result is a full media item plus why it matched. */
export interface SearchHit extends MediaItem {
  match: SearchMatch;
}

export interface SearchResults extends Pagination {
  items: SearchHit[];
  /** Echoed back by the server after normalization/trimming. */
  query: string;
}

export interface SearchSuggestion {
  value: string;
  kind: 'title' | 'tag';
}

// ---------------------------------------------------------------------------
// App settings (mirrors backend/src/services/settings.ts)
// ---------------------------------------------------------------------------

/** Which service runs transcriptions. Mirrors the `transcription_provider` enum. */
export type TranscriptionProvider = 'GROQ' | 'GOOGLE';

export interface AppSettings {
  provider: TranscriptionProvider;
  model: string;
  /** True when nothing has been saved yet, so the UI is showing the defaults. */
  isDefault: boolean;
}

export interface AppSettingsResponse extends AppSettings {
  /** Per-provider fallback model, supplied by the server so the UI never hardcodes one. */
  defaultModels: Record<TranscriptionProvider, string>;
  /** Which providers actually have credentials — a job fails without them. */
  available: Record<TranscriptionProvider, boolean>;
}
